version: "3.8"
services:
  nodeserver:
    image: ghcr.io/kakhavai/kian-wiki-nodeserver
    build:
      context: ./
    expose:
      - 8000
    depends_on:
      - database
  database:
    image: ghcr.io/kakhavai/kian-wiki-database
    build:
      context: ./postgres
    container_name: anything
    hostname: database
    restart: always
    environment:
      - DB_DIALECT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
  nginx:
    image: ghcr.io/kakhavai/kian-wiki-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - nodeserver
