version: "3.8"
services:
  nodeserver:
    build:
      context: ./
    expose:
      - 8000
    depends_on:
      - database
  database:
    image: postgres
    hostname: database
    environment:
      - DB_DIALECT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - nodeserver
