version: "3.8"
services:
  nodeserver:
    image: ghcr.io/kakhavai/kian-wiki-nodeserver
    expose:
      - 8000
      - 3000
    depends_on:
      - database
    environment:
      - DB_DIALECT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
  database:
    image: ghcr.io/kakhavai/kian-wiki-database
    container_name: kian-wiki-database
    hostname: database
    restart: always
    environment:
      - DB_DIALECT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
  nginx:
    image: ghcr.io/kakhavai/kian-wiki-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeserver
    environment:
      - NODE_ENV
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 